### ISSUE TITLE
Access-Control-Request-Method header does not match allowed methods. CORS headers will not be applied

### ISSUE THREAD

**Issue by oyermolenko** [alerta/angular-alerta-webui#105] opened 2017-11-22 11:48 UTC
Hi, 

Could someone clarify why I'm getting this error? Alerta seems to me works. But ...

Oleksandr Yermolenko

`[Wed Nov 22 12:43:30.497947 2017] [:error] [pid 6071] 2017-11-22 12:43:30,497 - flask_cors.core[6071]: INFO - The request's Access-Control-Request-Method header does not match allowed methods. CORS headers will not be applied. [in /usr/lib/python2.7/site-packages/flask_cors/core.py:202]
[Wed Nov 22 12:43:32.527423 2017] [:error] [pid 6073] 2017-11-22 12:43:32,527 - flask_cors.core[6073]: INFO - The request's Access-Control-Request-Method header does not match allowed methods. CORS headers will not be applied. [in /usr/lib/python2.7/site-packages/flask_cors/core.py:202]`

environment:
pip list
alerta (5.0.9)
alerta-server (5.0.3)
backports.ssl-match-hostname (3.4.0.2)
bcrypt (3.1.4)
blinker (1.4)
certifi (2017.11.5)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
configobj (4.7.2)
contextlib2 (0.5.5)
decorator (3.4.0)
ethtool (0.8)
Flask (0.12.2)
Flask-Compress (1.4.0)
Flask-Cors (3.0.3)
idna (2.6)
iniparse (0.4)
itsdangerous (0.24)
Jinja2 (2.10)
MarkupSafe (1.0)
perf (0.1)
pip (9.0.1)
psycopg2 (2.7.3.2)
pycparser (2.18)
pycurl (7.19.0)
pygobject (3.22.0)
pygpgme (0.3)
PyJWT (1.5.3)
pyliblzma (0.5.3)
pymongo (3.5.1)
python-dateutil (2.6.1)
python-linux-procfs (0.4.9)
pytz (2017.3)
pyudev (0.15)
pyxattr (0.5.1)
raven (6.1.0)
requests (2.18.4)
schedutils (0.4)
setuptools (0.9.8)
six (1.11.0)
slip (0.4.0)
slip.dbus (0.4.0)
tabulate (0.8.1)
urlgrabber (3.10)
urllib3 (1.22)
virtualenv (1.10.1)
Werkzeug (0.12.2)
yum-metadata-parser (1.1.4)

**Comment by satterly** [comment] 2017-11-22 13:51
What URL is this error for? Is this error generated when HTTP requests are coming from the browser, CLI or curl or elsewhere?

Please share your API server configuration (redact any API keys, username/passwords) and your web browser `config.js`, if it is the source of these requests. Thanks.

**Comment by oyermolenko** [comment] 2017-11-22 14:39
`aae@fusion> cat /etc/alertad.conf 
DEBUG = False

AUTH_REQUIRED = True
CUSTOMER_VIEWS = True

SECRET_KEY='L7h0%Z0dhdA6wK$%ygpkEyq5toxl&3%)'

DATABASE_URL = 'mongodb://localhost:27017/?connectTimeoutMS=300000'
DATABASE_NAME = 'monitoring'

CORS_ORIGINS = [
  'http://fusion.hetz.crp',
  'https://fusion.hetz.crp',
  'http://localhost'
]

PLUGINS=['reject']

ADMIN_USERS = [
  'aa@company.com',
  'aae@company.com'
]

ALLOWED_ENVIRONMENTS=[ 'Project1', 'Project2', 'Project3', 'Project4', 'Project5' ]
aae@fusion>`

**Comment by oyermolenko** [comment] 2017-11-22 14:39
`aae@fusion> cat /etc/httpd/conf.d/alerta.conf
Listen 8080
<VirtualHost *:8080>
  ServerName fusion.hetz.crp
  WSGIDaemonProcess alerta processes=5 threads=5
  WSGIProcessGroup alerta
  WSGIScriptAlias / /var/www/api.wsgi
  WSGIPassAuthorization On
  ErrorLog /var/log/httpd/error.log
  CustomLog /var/log/httpd/access.log combined
</VirtualHost>
<VirtualHost *:80>
  ProxyPass /api http://localhost:8080
  ProxyPassReverse /api http://localhost:8080
  DocumentRoot /var/www/html
  <Directory /var/www/html>
    Require all granted
  </Directory>
</VirtualHost>
aae@fusion>`

**Comment by oyermolenko** [comment] 2017-11-22 14:41
aae@fusion> cat /etc/httpd/conf.d/alerta.conf
Listen 8080
<VirtualHost *:8080>
  ServerName fusion.hetz.crp
  WSGIDaemonProcess alerta processes=5 threads=5
  WSGIProcessGroup alerta
  WSGIScriptAlias / /var/www/api.wsgi
  WSGIPassAuthorization On
  ErrorLog /var/log/httpd/error.log
  CustomLog /var/log/httpd/access.log combined
</VirtualHost>
<VirtualHost *:80>
  ProxyPass /api http://localhost:8080
  ProxyPassReverse /api http://localhost:8080
  DocumentRoot /var/www/html
  <Directory /var/www/html>
    Require all granted
  </Directory>
</VirtualHost>
aae@fusion>

**Comment by oyermolenko** [comment] 2017-11-22 14:47
`aae@fusion> cat api.wsgi
#!/usr/bin/env python
from alerta import app as application
aae@fusion> 

aae@fusion> cat html/config.js
'use strict';

angular.module('config', [])
  .constant('config', {
    'endpoint'    : "http://fusion.hetz.crp:8080",
    'provider'    : "basic", // google, github, gitlab, saml2 or basic
    'client_id'   : "",
    'github_url'  : null,  // for github enterprise provider only
    'gitlab_url'  : "https://gitlab.com",  // for gitlab provider only

    'colors'      : {
      'severity': {
        'fatal'        : '#000000',  // black
        'critical'     : '#D8122A',
        'major'        : '#EA680F',
        'minor'        : '#FFBE1E',
        'warning'      : '#BA2222',
        'indeterminate': '#A6ACA8',
        'cleared'      : '#00AA5A',
        'normal'       : '#00AA5A',
        'ok'           : '#00AA5A',
        'informational': '#00A1BC',
        'debug'        : '#9D006D',
        'security'     : '#333333',
        'unknown'      : '#A6ACA8'
      },
      'text': 'white',
      'highlight': 'lightgray'
    },
    'severity'    : {
      'fatal': 0
    },
    'dates': {
      'shortTime' : 'shortTime',  // 1:39 PM
      'mediumDate': 'medium', // Apr 26, 2016 1:39:44 PM
      'longDate'  : 'EEEE, MMMM d, yyyy h:mm:ss.sss a (Z)'  // Tuesday, April 26, 2016 1:39:43.987 PM (+0100)
    },
    'audio'       : {
      'new'  : '/audio/Bike Horn.mp3'
    },
    'tracking_id': 'UA-NNNNNN-N'
  });
aae@fusion>`

**Comment by oyermolenko** [comment] 2017-11-23 06:47
`aae@fusion> cat /etc/uwsgi.ini
[uwsgi]
chdir = /var/www
mount = /api=api.wsgi
callable = app
manage-script-name = true

master = true
processes = 5
#logger = syslog:alertad

socket = /var/run/uwsgi/uwsgi.sock
chmod-socket = 664
uid = apache
gid = apache
vacuum = true

die-on-term = true`

**Comment by satterly** [comment] 2017-11-23 13:48
What URL is this error for? Is this error generated when HTTP requests are coming from the browser, CLI? If you use curl to query the URL do you get the same error?

**Comment by cyberflow** [comment] 2017-11-23 14:25
@oyermolenko I had a similar problem, try to add this to `/etc/alertad.conf`:
```
CORS_ORIGINS = [
	'*'
]
```

**Comment by oyermolenko** [comment] 2017-11-24 08:19
Hi, again,

1.  if I do nothing with alertad.conf errors appear every 2-3 secs.

2. if I tranform my alertad.conf to
...
CORS_ORIGINS = [
  'fusion.hetz.crp',
  'localhost'
]
... and errors  appear a few times per 5 minutes

3. if I set 
CORS_ORIGINS = [
	'*'
] 
errors have gone (disappear) ... thanks @cyberflow 

being keep thinking how to catch those events in case I avoid [3]
I guess I can lose a few nagios events. Maybe ...

@satterly I would not say that those errors generated by browser or cli curl (firefox was closed). At this moment I have no idea what URL for. Just observe these errors tail -f error.log

Oleksandr

**Comment by satterly** [comment] 2017-11-29 12:37
CORS errors will not prevent Alerta from receiving alerts. They can only be caused by a misconfigured web UI setup. I would ignore them unless they are preventing Alerta from working. I'll close this issue for now. If you have further information to aid in the investigation we can reopen it.

**Closed by satterly** 2017-11-29 12:37 UTC
Labels: question
